---
- name: Jira patch lifecycle handler
  hosts: all

  sources:
    - ansible.eda.webhook: {}

  rules:

    - name: "Jira | Patch Windows - launch patch"
      condition: event.payload is defined and (event.payload.issue_status is not defined or event.payload.issue_status != "Revert Patch")
      action:
        run_job_template:
          name: "Hybrid Patch Workflow"
          organization: "IIS Demo Lab"
          job_args:
            extra_vars:
              jira_ticket_id:   "{{ event.payload.issue_key | default('CHG-0') }}"
              jira_summary:     "{{ event.payload.issue_summary | default('Manual trigger') }}"
              target_hosts:     "windows"
              dry_run:          false
              aap_job_url_base: "https://aap.iisdemolab.click"

    - name: "Jira | Revert Patch - launch rollback"
      condition: event.payload is defined and event.payload.issue_status == "Revert Patch"
      action:
        run_job_template:
          name: "Rollback Patch"
          organization: "IIS Demo Lab"
          job_args:
            extra_vars:
              jira_ticket_id:   "{{ event.payload.issue_key | default('CHG-0') }}"
              jira_summary:     "{{ event.payload.issue_summary | default('Manual rollback') }}"
              target_hosts:     "windows"
              aap_job_url_base: "https://aap.iisdemolab.click"
