apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../amboy-baremetal/gitops/manifests
patches:
  - target:
      version: v1
      kind: ServiceAccount
      name: amboy
      namespace: iis-ai-ui
    patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: amboy
        namespace: iis-ai-ui
      $patch: delete
