---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pd-monitoring
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: default
  source:
    repoURL: https://github.com/sankat447/company-demos
    targetRevision: feature/police-department-v1
    path: police-department/manifests/monitoring
    directory:
      include: "pd-*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: pd-cctv
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - ServerSideApply=true
