---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pd-namespaces
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/sankat447/company-demos
    targetRevision: HEAD
    path: police-department/manifests/namespaces
    directory:
      include: "pd-*.yaml"
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
