---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pd-pipeline
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/sankat447/company-demos
    targetRevision: HEAD
    path: police-department/manifests/pipeline
    directory:
      include: "pd-*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: pd-cctv
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
