#!/usr/bin/env bash
# Regenerate config.js from the live backend's terraform outputs.
set -euo pipefail
TF="$(cd "$(dirname "${BASH_SOURCE[0]}")/../bir-backend/terraform" && pwd)"
export AWS_PROFILE="${AWS_PROFILE:-rhoai-demo}" AWS_REGION="${AWS_REGION:-us-east-1}"
o(){ terraform -chdir="$TF" output -raw "$1"; }
cat > "$(dirname "${BASH_SOURCE[0]}")/config.js" <<JS
// Live stack config (public client identifiers — not secrets). Generated by gen-config.sh.
window.BIR_CONFIG = {
  region: '$(o region)',
  userPoolId: '$(o auth_user_pool_id)',
  clientId: '$(o auth_user_pool_client_id)',
  graphql: '$(o api_graphql_endpoint)',
  restBase: '$(o payments_rest_base)',
  kbBucket: '$(o kb_bucket)',
};
JS
echo "wrote config.js"
