#!/usr/bin/env python3
"""Regenerate manifests/pipeline/pd-cv-scripts-configmap.yaml from cv-scripts/*.py.

The CV helper scripts are mounted into pd-task-vlm-caption steps from this
ConfigMap instead of being inlined, because Tekton's place-scripts init
container passes every inline step script through argv (~100 KB ceiling,
LESSONS_LEARNED 17.40). Edit the .py files, then run this; tests/ checks
the two stay in sync.
"""
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
src = root / "manifests/pipeline/cv-scripts"
out = root / "manifests/pipeline/pd-cv-scripts-configmap.yaml"
lines = [
    "# GENERATED by scripts/gen_cv_scripts_configmap.py from manifests/pipeline/cv-scripts/ — do not edit by hand.",
    "apiVersion: v1",
    "kind: ConfigMap",
    "metadata:",
    "  name: pd-cv-scripts",
    "  namespace: pd-cctv",
    "  labels:",
    "    app.kubernetes.io/part-of: police-department",
    "data:",
]
for f in sorted(src.glob("*.py")):
    lines.append(f"  {f.name}: |")
    lines += [("    " + l) if l else "" for l in f.read_text().splitlines()]
out.write_text("\n".join(lines) + "\n")
print(f"wrote {out.relative_to(root)} ({out.stat().st_size} bytes, {len(list(src.glob('*.py')))} scripts)")
